import { caseStudies, type CaseStudy } from "@/lib/content";

// Dedicated-page copy; the shared work cards keep their existing content.
const details: Record<string, Partial<CaseStudy>> = {
  "gdg-on-campus": {
    eyebrow: "Grassroots developer ecosystem growth",
    positioning: "A community-led growth engine connecting technical enablement, career opportunity and industry partnerships.",
    role: "Ecosystem Lead & Operations Director",
    timeframe: "4-year lifecycle",
    metric: "7,000+",
    metricLabel: "active technical builders; 600% organic expansion from 1,000",
    summary: "Scaled a developer registry into a sustained ecosystem through multi-year strategy, developer acquisition, volunteer operations and enterprise alignment.",
    challenge: "Regional developer hubs often face low engagement, cohort drop-off and fragmented event programming. The challenge was to turn a baseline 1,000-member registry into a high-retention technical ecosystem that drives zero-CAC product adoption, builds technical talent density and delivers reliably at regional scale.",
    approach: [
      "Shifted from isolated events to technical enablement, career pathways, hands-on build sprints and direct industry integration.",
      "Built a growth flywheel: problem identification, community alignment, structured program design, targeted activation, real-world opportunity and long-term continuity.",
      "Structured, trained and led 300+ contributors across logistics, technical content, media, marketing and systems operations.",
      "Secured sponsorships and support with Google for Developers, CC Hub and CHAOSS Africa, and delivered 15+ technology events and builder activations.",
    ],
    outcome: "Expanded the developer network from 1,000 to 7,000+ active engineering members, a 600% organic increase. The Build with AI campaign ranked #1 in Africa. A zero-CAC distribution model supported sponsor tools and technology programs, while recurring pathways helped students become project builders, open-source contributors and industry professionals.",
    lesson: "A community is not just a mailing list or attendance count—it is a value-delivery engine. By aligning student career incentives with structured technical pathways, community-led growth becomes the most effective, zero-CAC pipeline for tech adoption and talent acquisition.",
  },
  "build-with-ai": {
    eyebrow: "Developer activation & AI adoption",
    positioning: "A hands-on developer activation sprint series moving builders from curiosity to API onboarding and prototype shipping.",
    role: "Lead Technical Program Director & Developer Advocacy Lead",
    timeframe: "March 2024 – August 2026 · 4 editions",
    metric: "2,500+",
    metricLabel: "builders activated directly; 10,000+ ecosystem participants reached",
    summary: "Four campaign editions replaced passive AI workshops with practical build sprints, standardized tooling and live mentorship.",
    challenge: "Slide-led workshops left attendees watching instead of coding. API key configuration, fragmented tooling and complex environment setup made it difficult to move from conceptual LLM knowledge to practical implementation, while limited real-time guidance prevented builders from taking projects from localhost to deployment.",
    approach: [
      "Designed a three-stage onboarding funnel: passive curiosity, API onboarding and functional prototype shipping, with a mandatory hands-on format replacing slide-only sessions.",
      "Used standardized starter repositories and interactive Jupyter/Kaggle notebooks for Generative AI, Gemini and Gemma integrations, prompt engineering, dataset analysis and LLM orchestration.",
      "Provided pre-configured environments, step-by-step setup guides and mentor pods to resolve API configuration and code errors in real time.",
      "Managed four editions and partnered with Ilorin Innovation Hub for high-bandwidth infrastructure, overnight hack nights and regional engineer access. Coordinated mentors, code submissions, pull-request reviews and deployed project evaluation.",
    ],
    outcome: "Ranked #1 among Build with AI activations across Google developer chapters in Africa and featured in Google's August 2026 Developer Community Newsletter. Activated 2,500+ builders directly within a broader reach of 10,000+ participants. The campaign shifted entirely to active API onboarding and prototype shipping, producing dozens of functional AI applications, custom Gemini API tools and open-source contributions.",
    lesson: "Product adoption is not measured by event attendance or vanity metrics; true developer activation is validated only when a builder configures an API key, executes code, and successfully deploys a functional prototype into a live environment.",
  },
  careerfest: {
    eyebrow: "Program operations & talent ecosystem architecture",
    positioning: "A flagship career and talent summit connecting students, employers and academic stakeholders across four editions.",
    role: "Lead Program Director & Operations Lead",
    timeframe: "2023 – 2026 · 4 editions",
    metricLabel: "cumulative in-person attendees across four editions",
    ownershipNote: "Core organizing lead and Head of Program Operations across four consecutive editions; Adam is not the founder of CareerFest.",
    summary: "Evolved a keynote conference into a multi-track talent hub with career-readiness workshops, portfolio reviews, recruitment booths and direct hiring pathways.",
    challenge: "Campus career events often leave a gap between presentations and tangible opportunity. Employers face inefficient access to job-ready early-career candidates, while students lack clear routes to internships and entry-level roles. At summit scale, venue capacity, crowd flow, registration and partner delivery add operational friction.",
    approach: [
      "Structured a multi-sided talent marketplace connecting students, corporate partners, industry executives and academic stakeholders.",
      "Developed four editions into a multi-track experience with hands-on workshops, resume and portfolio reviews, corporate recruitment booths and hiring tracks.",
      "Designed participant pipelines linking graduating talent and student developers to corporate opportunities and mentorship.",
      "Directed venue selection, staging, capacity planning, credentialing and crowd flow for audiences exceeding 2,600. Managed sponsorships, recruitment activations and speaker hospitality, and trained 100+ volunteers across logistics, registration, protocol, media and partner operations.",
    ],
    outcome: "Sustained 6,000+ cumulative in-person attendees: approximately 1,000 in each of the first two editions, 2,600+ in the third and 1,300+ high-intent participants in the fourth. Recurring sponsor and recruiter participation supported a regional and national talent pipeline, connecting students to entry-level roles, technology internships and structured industry mentorship.",
  },
  epex: {
    title: "Engineering Project Exhibition (EPEX)",
    eyebrow: "Hardware product operations & technical systems",
    positioning: "An inter-institutional hardware and systems showcase linking working engineering prototypes with expert evaluation and industry exposure.",
    role: "Co-Chairman & Director of Hardware Product Operations (2025); Executive Chairman & General Chair (2027, in planning)",
    timeframe: "May 2025 · May 2027 in planning",
    metric: "2,000+",
    metricLabel: "engineering practitioners and technical builders reached",
    summary: "Delivered the inaugural engineering showcase across mechanical, electromechanical, embedded systems and robotics disciplines, with dedicated high-school STEM immersion.",
    challenge: "Theory-focused technical education leaves gaps in physical prototyping, testing and hardware validation. Student engineers lack suitable facilities and industry exposure, while institutionally isolated projects receive limited external scrutiny of manufacturability, commercial potential and corporate R&D opportunities.",
    approach: [
      "Established evaluation frameworks for structural integrity, hardware safety, manufacturability and build quality before showcase admission.",
      "Organized mechanical systems, electromechanical automation, embedded IoT and robotics tracks, with judging panels of department heads, engineering practitioners and industry investors.",
      "Coordinated inter-state delegations, equipment freight safety and hardware load-in. Planned booth layouts and high-voltage/electromechanical power staging for safe, continuous exhibition access.",
      "Delivered secondary-school STEM immersion across Kwara State through guided tours, safe delegation movements and hands-on hardware demonstrations.",
    ],
    outcome: "Engaged 2,000+ engineering builders across regional institutions, showcased and tested dozens of working prototypes before expert panels and industrial investors, and introduced hundreds of secondary-school students to hands-on engineering. Planning for May 2027 targets a nationwide engineering congress, expanded booth capacity, increased project seed grants and corporate R&D recruitment pathways.",
  },
  "aiesec-brand-week": {
    title: "AIESEC Brand Sprint",
    eyebrow: "Multi-program operations & campaign strategy",
    positioning: "Six program tracks brought together through one seven-day ecosystem and stakeholder activation sprint.",
    role: "Organizing Committee President & Campaign Operations Director",
    timeframe: "July – November 2025",
    metric: "2,000+",
    metricLabel: "cumulative participants across six program tracks",
    summary: "Led a 30-person operations unit to deliver a coordinated AIESEC campaign spanning professional development, global exchange, community impact, sport, culture and partner exhibitions.",
    challenge: "Multi-audience campaigns face siloed teams, conflicting resource allocation and fragmented messaging. Moving participants between different formats increases drop-off, while delivery across multiple venues creates risks of schedule collisions, credentialing confusion and technical failures.",
    approach: [
      "Built one seven-day blueprint for six tracks: career masterclasses; global exchange and leadership discovery; community outreach; athletic and wellness tournaments; university cultural and talent mixers; and corporate, SME and alumni exhibitions.",
      "Unified registration, credentialing and communications into a shared onboarding pipeline, with one narrative and visual identity for students, sponsors, faculty and civic leaders.",
      "Directed 30+ contributors across logistics, creative media, speaker management and sponsor fulfillment. Used daily standups and centralized asset management to coordinate schedules, equipment and venue clearances.",
      "Managed corporate, SME and alumni relationships, delivering partner commitments, booth allocations and brand placement in full.",
    ],
    outcome: "Reached 2,000+ attendees across six tracks with zero logistical delays, venue schedule collisions or vendor drop-offs during the seven-day sprint. Structured exhibitions and targeted engagement delivered partner value, while volunteer onboarding expanded the pipeline for future AIESEC leadership cohorts.",
    lesson: "Multi-audience campaigns do not fail from a lack of content; they fail from a lack of unified infrastructure. Coherence across complex portfolios requires a single, disciplined operational heartbeat.",
  },
  devcenter: {
    title: "DevCenter",
    eyebrow: "Pan-African developer relations & ecosystem operations",
    positioning: "Connecting a nationwide developer network with infrastructure partners, structured build sprints and industry opportunities.",
    role: "Ecosystem & Partnerships Lead / Developer Operations",
    timeframe: "Nationwide footprint across Nigeria",
    metricLabel: "software developers and builders in the network",
    summary: "Aligned partnerships, developer communications and mentorship across a 23,000+ builder network to support real-world software delivery and career access.",
    challenge: "Developer communities across Nigeria and Africa remain fragmented without shared infrastructure, standardized build pipelines or sustained engagement. Isolated projects offer limited exposure to production architectures and code review, while grassroots talent lacks direct bridges to cloud partners, developer tooling and enterprise opportunities.",
    approach: [
      "Sourced and integrated cloud and tooling partners, including RumptyCloud, to provide infrastructure and tooling grants for developer activations.",
      "Designed 30-day build sprints and hackathons with technical tracks, senior industry judges and evaluation based on repository activity, code quality and deployed applications.",
      "Built peer-learning loops, engineering-leader AMAs and talent exposure pathways connecting early-career builders with technology companies.",
      "Managed multi-channel communications across 23,000+ engineers, designers and builders. Coordinated regional leads, national campaigns and partner tracking, alongside mentorship, office hours and pull-request reviews.",
    ],
    outcome: "Drove engagement across a pan-African developer network of 23,000+ builders across Nigeria. National 30-day sprints produced dozens of functional products and open-source contributions. Developer tool adoption supported repeat sponsorships and expanded integrations, while public showcases, industry AMAs and recruitment pathways increased builder visibility and access to global opportunities.",
    lesson: "Developer ecosystems are not sustained by just member counts; their real value lies in liquidity—the speed and reliability with which builders access tools, build real-world software, and unlock high-value career opportunities.",
  },
};

export const caseStudyDetails: CaseStudy[] = caseStudies.map((study) => ({
  ...study,
  ...details[study.slug],
}));
